title: Jukka-Pekka Jauhiainen # your name (or website title) here
logo: "https://cdn.pixabay.com/photo/2012/04/18/19/03/snake-37585_960_720.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
